// the main anniversary letter — sealed envelope section
const MAIN_LETTER = {
  date: "february 14, 2027",
  greeting: "my love,",
  paragraphs: [
    "i keep trying to find a way to start this that doesn't sound like every other letter i've written you, and i can't, so i'll just start plain and simple. four years. i've said that number in my head so many times these past few weeks and it still doesn't feel real. four years since you said yes on a day that already belonged to everyone else (valentines), and somehow made it belong to us instead.",
    "i think about senior high sometimes, more than i probably let on. i think about how i used to look forward to seeing you sit down before class even started, and how small the interaction we had felt at the time, and how it wasn't small at all. i admired you quietly for so long. i didn't say anything because i was scared \u2014 scared of ruining something that felt good even from a distance, scared of wanting something i didn't think i'd get to have. i had already told myself i probably wouldn't let myself fall for someone again. and then i did anyway, because you came, and that was the best thing that ever happened. then, on december 19, 2022, i said it out loud, half-convinced you'd say NO or worse, say NOTHING. but you said it back. i think i forgot how to breathe for a second. i wasn't ready for you to feel the same. i think some part of me is still not fully over the shock of it, even now.",
    "after that, the weeks of just talking, flirting, getting closer, and then february 14, 2023. you said yes. i probably said something dumb right after, i don't even remember what, but you probably do. that was the start of it. the real start.",
    "four years later and we've changed so much it's almost funny to look back. we've had the easy days \u2014 the ones that don't need explaining, the ones where everything just works. we've had the ordinary ones too, which i think i love just as much, maybe more. and we've had the hard ones. i'm not going to pretend we haven't. we're both emotional people, we both have our moods, and sometimes they collide in ways that don't make sense until after they've already happened. i know i go quiet when things get hard. i know that's not always fair to you. and i know you're usually the one who moves toward me instead of away, even when i've made that difficult, even when i don't deserve it yet. i don't think i say thank you for that enough. so \u2014 thank you. for staying close when i pull back. for choosing the real, complicated, moody version of me, avoidant and all.",
    "i want to tell you how beautiful you are, and i mean that, but i don't want that to be the only thing i say, because it isn't even the part i think about most. i think about how you take care of me when i'm sick without me having to ask. i think about how you spend on me even when things are tight for you. i think about the way you laugh at my dumb jokes like they're actually funny. i think about how you disappear into a book for hours \u2014 fantasy, romance, history, politics, anything \u2014 and how your face runs through a hundred emotions while you read. i think about how you don't really post yourself online, but you post me, and what that says a lot about you. i think about your smell, how it makes me sleepy in the best way, how it feels like safety. i think about how you get quiet and focused when you're reading or painting or making something, and how i could watch that for a long time. and i think about your goofy side, the one that has nothing to do with any of the serious stuff, and i love it just as much.",
    "you deserve everything good this world has to give you, and i mean that without exaggeration. every soft morning. every good thing that exists. i want it all pointed at you. i can't hand you the universe, but i can keep showing up, keep learning you better, keep getting better at loving you the way you actually need instead of the way that's easiest for me. that's the promise i can actually keep, and i intend to keep it.",
    "happy four years, love. here's to more ordinary days, more silly arguments that end in us laughing about it later, and more february 14ths, for as long as you'll have me."
  ],
  closing: "i love you, today and every year after,",
  signature: "val"
};
